--- a/Makefile
+++ b/Makefile
@@ -1,4 +1,4 @@
-PREFIX = /usr/local
+PREFIX = /usr
 CFLAGS ?= -g -Wall -Wextra -Werror -Wno-unused-parameter -Wno-sign-compare -Wno-unused-function -Wno-unused-variable -Wno-unused-result -Wdeclaration-after-statement
 
 CFLAGS += -I. -DWLR_USE_UNSTABLE -std=c99
@@ -62,6 +62,6 @@
 	make release
 
 install:
-	mkdir -p ${DESTDIR}${PREFIX}/bin ${DESTDIR}${PREFIX}/share/man/man1
-	cp doc/hyprpicker.1 ${DESTDIR}${PREFIX}/share/man/man1
+	mkdir -p ${DESTDIR}${PREFIX}/bin ${DESTDIR}${PREFIX}/man/man1
+	cp doc/hyprpicker.1 ${DESTDIR}${PREFIX}/man/man1
 	cp build/hyprpicker ${DESTDIR}${PREFIX}/bin

